server:
  port: 7000
  tomcat:
    accesslog:
      enabled: true

management:
  context-path: '/management'
#  security:
#    enabled: false
#    roles: ACTRADMIN
  endpoints:
    web:
      base-path: '/actuator'
      exposure:
        include: health, info, metrics, env, conditions
    enabled:
      all: true
  endpoint:
    health:
      circuitbreakers:
        enabled: true
      probes:
        enabled: true # Local testing purpose
      liveness:
        enabled: true
        include: livenessStateProbeIndicator
      readiness:
        enabled: true
        include: readinessStateProbeIndicator
      show-details: always

security:
  enabled: true
  user:
    name: act
    password: act
